# Generated by Django 5.1.1 on 2024-09-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('book_image', models.ImageField(default='book.jpg', upload_to='images/')),
            ],
            options={
                'db_table': 'bookcard',
            },
        ),
    ]
