# Generated by Django 5.1.1 on 2024-09-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcardapp', '0002_alter_card_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='book_images')),
            ],
            options={
                'db_table': 'BOOKCARD',
            },
        ),
        migrations.DeleteModel(
            name='card',
        ),
    ]
