# Generated by Django 5.1.1 on 2024-09-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcardapp', '0004_books_delete_book'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='bookcard',
        ),
    ]
