# Generated by Django 5.1.1 on 2024-09-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcardapp', '0007_alter_books_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='booktable',
        ),
    ]
